AWS_S3/AWS_S3/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('buckets.urls')),
    path('admin/', admin.site.urls),
]

AWS_S3/buckets/urls.py
from django.contrib import admin
from django.urls import path,include
from buckets import views

app_name='buckets'


urlpatterns = [
path('',views.home,name='home'),
path('login/',views.login,name='login'),
path('create/',views.create,name='create'),
path('delete/',views.delete,name='delete'),
path('copy/',views.copy,name='copy'),
path('move/',views.move,name='move'),
path('create/<str:fn>/',views.files),
path('login/<str:fn>/',views.files),
path('delete/<str:fn>/',views.files),
path('login/<str:fn>/upld.html',views.upload),
path('create/<str:fn>/upld.html',views.upload),
path('delete/<str:fn>/upld.html',views.upload),
]

AWS_S3/buckets/models.py
from django.db import models

# Create your models here.

AWS_S3/buckets/views.py
from django.shortcuts import render
import boto3
from django.contrib import messages

# Create your views here.
def home(request):
    if request.method == 'POST':
        global aid,sak 
        aid=request.POST.get('aid')
        log=request.POST.get('log')
        sak=request.POST.get('sak')
        try:
            if log:
                if aid and sak:
                    s3=boto3.resource(
                        service_name='s3',
                        region_name='us-east-1',
                            aws_access_key_id = aid,
                        aws_secret_access_key = sak,)
                    for i in s3.buckets.all():
                        break 
                    return render(request,'buckets/home.html',{'s':True})
                else:
                    messages.error(request,'Please Enter Access Key Id and Secret Access Key')
                    return render(request,'buckets/home.html')
        except:
            messages.error(request,'Invalid Access Key Id and Secret Access Key')
            return render(request,'buckets/home.html')
    return render(request,'buckets/home.html')

def login(request):
    if request.method == 'POST':
        s3=boto3.resource(
                       service_name='s3',
                    region_name='us-east-1',
                        aws_access_key_id = aid,
                      aws_secret_access_key = sak,) 
        lb=request.POST.get('lb')
        if lb:
            return render(request,'buckets/login.html',{'lbs':[i for i in s3.buckets.all()]})   

    return render(request,'buckets/login.html')              

def create(request):
    if request.method == 'POST':

        s3=boto3.resource(
                       service_name='s3',
                    region_name='us-east-1',
                        aws_access_key_id = aid,
                      aws_secret_access_key = sak,) 
        n=request.POST.get('name')
        cr=request.POST.get('cr')

        if cr and n:
            if n not in [i.name for i in s3.buckets.all()]:
                try:
                    s3.create_bucket(Bucket=n)
                    messages.success(request,'Bucket successfully created')
                    return render(request,'buckets/create.html',{'lbs':[i for i in s3.buckets.all()]})
                except:
                    messages.error(request,'Invalid Bucket name please try a diffrent name')
                    return render(request,'buckets/create.html',{'lbs':[i for i in s3.buckets.all()]})
            else:
                messages.error(request,'Bucket aldready exist please try a diffrent name')
                return render(request,'buckets/create.html',{'lbs':[i for i in s3.buckets.all()]})
        else:
            messages.error(request,'Please Enter Bucket name')
            return render(request,'buckets/create.html',{'lbs':[i for i in s3.buckets.all()]})   
    
    return render(request,'buckets/create.html')  



def delete(request):
    if request.method == 'POST':

        s3=boto3.resource(
                       service_name='s3',
                    region_name='us-east-1',
                        aws_access_key_id = aid,
                      aws_secret_access_key = sak,) 
        
        n=request.POST.get('name')
        dl=request.POST.get('del')   
        
        if dl and n:
            if n in [i.name for i in s3.buckets.all()]:
                bck=s3.Bucket(n)
                bck.objects.all().delete()
                bck.delete()
                messages.success(request,f'{n} Deleted successfully click on List Buckets to verify')
                return render(request,'buckets/delete.html',{'lbs':[i for i in s3.buckets.all()]})
            else:
                messages.error(request,'Bucket does not exist please try a valid name')
                return render(request,'buckets/delete.html',{'lbs':[i for i in s3.buckets.all()]})
        else:
            messages.error(request,'Please Enter Bucket name')
            return render(request,'buckets/delete.html',{'lbs':[i for i in s3.buckets.all()]})
   
    return render(request,'buckets/delete.html')  

def copy(request):
    if request.method == 'POST':

        s3=boto3.resource(
                       service_name='s3',
                    region_name='us-east-1',
                        aws_access_key_id = aid,
                      aws_secret_access_key = sak,) 
        
        sbn=request.POST.get('sbname')
        sfn=request.POST.get('sfname')
        dbn=request.POST.get('dbname')
        dfn=request.POST.get('dfname')
        cf=request.POST.get('cf')   

        if cf:
            if sbn and sfn and dbn and dfn:
                nbm=[i.name for i in s3.buckets.all()]
                if sbn in nbm and dbn in nbm:
                    mys=s3.Bucket(sbn)
                    myd=s3.Bucket(dbn)
                    nsfm=[i.key for i in mys.objects.all()]
                    ndfm=[i.key for i in myd.objects.all()]
                    if sfn in nsfm and dfn in ndfm:
                        cs={
                            'Bucket':sbn,
                            'Key':sfn
                        }
                        buck = s3.Bucket(dbn)
                        buck.copy(cs,dfn)
                        messages.success(request,f'Copied content of {sbn}/{sfn} to {dbn}/{dfn} successfully')
                    else:
                        messages.error(request,'invalid source or destination file name please enter valid names')
                        return render(request,'buckets/copy.html')
                else:
                    messages.error(request,'invalid source or destination bucket name please enter valid names')
                    return render(request,'buckets/copy.html')
                                
            else:
                messages.error(request,'Please Enter all the * fields')
                return render(request,'buckets/copy.html')   
    return render(request,'buckets/copy.html') 


def move(request):
    if request.method == 'POST':

        s3=boto3.resource(
                       service_name='s3',
                    region_name='us-east-1',
                        aws_access_key_id = aid,
                      aws_secret_access_key = sak,) 
        
        sbn=request.POST.get('sbname')
        sfn=request.POST.get('sfname')
        dbn=request.POST.get('dbname')
        dfn=request.POST.get('dfname')
        mf=request.POST.get('mf')   

        if mf:
            if sbn and sfn and dbn:
                nbm=[i.name for i in s3.buckets.all()]
                if sbn in nbm and dbn in nbm:
                    myd=s3.Bucket(sbn)
                    nsfd=[i.key for i in myd.objects.all()]
                    if sfn in nsfd:
                        s3.Bucket(dbn).put_object(Key=sfn)
                        css={
                            'Bucket':sbn,
                            'Key':sfn
                        }
                        bck = s3.Bucket(dbn)
                        bck.copy(css,sfn)
                        s3.Object(sbn,sfn).delete()
                        messages.success(request,f'Moved {sfn} from {sbn} to {dbn} successfully',{'lfs'})
                    else:
                        messages.error(request,'invalid source or destination file name please enter valid names')
                        return render(request,'buckets/move.html')
                else:
                    messages.error(request,'invalid source or destination bucket name please enter valid names')
                    return render(request,'buckets/move.html')
                                
            else:
                messages.error(request,'Please Enter all the * fields')
                return render(request,'buckets/move.html') 

    return render(request,'buckets/move.html') 

def files(request,fn: str):
    if request.method == 'POST':

        s3=boto3.resource(
                       service_name='s3',
                    region_name='us-east-1',
                        aws_access_key_id = aid,
                      aws_secret_access_key = sak,) 
        lf=request.POST.get('lf')
        crf=request.POST.get('crf')
        f=request.POST.get('fname')
        df=request.POST.get('df')
        crfo=request.POST.get('crfo')
        dfo=request.POST.get('dfo')

        myb=s3.Bucket(fn)

        if lf:
            return render(request,'buckets/files.html',{'lfs':[i.key for i in myb.objects.all()]})

        if crf:
            if f:
                s3.Bucket(fn).put_object(Key=f)
                messages.success(request,f'{f} created successfully click on List Files/Folder to verify')
                return render(request,'buckets/files.html',{'lfs':[i.key for i in myb.objects.all()]})
            else:
                messages.error(request,'Please Enter File name')
                return render(request,'buckets/files.html',{'lfs':[i.key for i in myb.objects.all()]})


        if df:
            if f:
                mfb=s3.Bucket(fn)
                if f in [i.key for i in mfb.objects.all()]:
                    s3.Object(fn,f).delete()
                    messages.success(request,f'{f} deleted  successfully click on List Files/Folder to verify')
                    return render(request,'buckets/files.html',{'lfs':[i.key for i in myb.objects.all()]})
                else:
                    messages.error(request,'File does not exist please try a valid name')
                    return render(request,'buckets/files.html',{'lfs':[i.key for i in myb.objects.all()]})
            else:
                messages.error(request,'Please Enter File name')
                return render(request,'buckets/files.html',{'lfs':[i.key for i in myb.objects.all()]}) 

        if crfo:
            if f:
                f+='/'
                s3.Bucket(fn).put_object(Key=f)
                messages.success(request,f'{f} created successfully click on List Files/Folder to verify')           

AWS_S3/buckets/templates/buckets/copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        *{
            box-sizing:border-box
            
        }
        
        
        body{
            background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
        }
        input{
            margin: 3px;
         border: 1px solid red; 
            padding: 7px; 
            margin: 10px;
        }
        .text{
            border-radius:10px 10px;
            padding: 10px;
            transition:1s;
        }
        .text:hover{
            box-shadow: inset 0 12px 16px 0 rgba(0,0,0,0.10),0 17px 50px 0 rgba(0,0,0,0.19);
        } 
        .button{
            color:white;
            padding:10px;
            text-align:center;
            cursor:pointer;
            background-color: rgb(66, 19, 119);
            transition: 1s;
            border-radius:10px 10px;
        }
        .button:hover{
            transform:translate(0,-3px);
            background:black;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
        h1{
            border-radius:10px 10px;
    
            transition:1s; 
        }
</style>



</head>
<body>
    <form method="POST">
        {% csrf_token %}
<center style="margin-top:100px ;">

    <div>
        <input type="text" placeholder="Source Bucket name (*)" name="sbname" class="text">
        <input type="text" placeholder="Source File name (*)" name="sfname" class="text">
    </div>
    <div>
        <input type="text" placeholder="Destination Bucket name (*)" name="dbname" class="text">
        <input type="text" placeholder="Destination File name (*) " name="dfname" class="text"><br>
    </div>
    <div>    
        <input type="submit" class="button" value="Copy File" name="cf"> 
    </div>

</center>
        
    </form>


            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
                
        <div style="height:495px ;"></div>
</body>
</html>

AWS_S3/buckets/templates/buckets/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
    
    body{

background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
}

    th, td {
  border-bottom: 1px solid rgb(173, 167, 206);
}

table{

    padding: 5px;
    font-family: serif;
}
input{
            margin: 3px;
         border: 1px solid red; 
            padding: 7px; 
            margin-top: 40px;
            margin-left: 40px;
        }
.text{
            border-radius:10px 10px;
            padding: 10px;
            transition:1s;
        }
        .button{
            color:white;
            padding:10px;
            text-align:center;
            cursor:pointer;
            background-color: rgb(66, 19, 119);
            transition: 1s;
            border-radius:10px 10px;
        }
        .button:hover{
            transform:translate(0,-3px);
            background:black;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }

</style>
    
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Enter Bucket name" name="name" class="text" >
        <input type="submit" class="button" value="Create Bucket" name="cr">

    </form>
    {% if lbs %}
    <table>
        <tr>
            <th><h1>Bucket Name</h1></th>
            <th><h1>Creation Date</h1></th>
        </tr>
        {% for i in lbs %}
        <tr>
            <td><h2><a href="{{i.name}}" style="color: black;">{{i.name}}</a></h2></td>
            <td><h2>{{i.creation_date}}</h2></td>
        </tr>
        {% endfor %}
    </table>
        {% endif %}

    
            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
                
    
        <div style="height: 675px;"></div>
</body>
</html>

AWS_S3/buckets/templates/buckets/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    
        body{
    
    background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
    }
    
        th, td {
      border-bottom: 1px solid rgb(173, 167, 206);
    }
    
    table{
    
        padding: 5px;
        font-family: serif;
    }
    input{
                margin: 3px;
             border: 1px solid red; 
                padding: 7px; 
                margin-top: 40px;
                margin-left: 40px;
            }
    .text{
                border-radius:10px 10px;
                padding: 10px;
                transition:1s;
            }
            .button{
                color:white;
                padding:10px;
                text-align:center;
                cursor:pointer;
                background-color: rgb(66, 19, 119);
                transition: 1s;
                border-radius:10px 10px;
            }
            .button:hover{
                transform:translate(0,-3px);
                background:black;
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
            }
    
    </style>
        

</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <input type="text" placeholder="Enter Bucket name" name="name" class="text" >
        <input type="submit" class="button" value="Delete Bucket" name="del">

    </form>
    {% if lbs %}
    <table>
        <tr>
            <th><h1>Bucket Name</h1></th>
            <th><h1>Creation Date</h1></th>
        </tr>
        {% for i in lbs %}
        <tr>
            <td><h2><a href="{{i.name}}" style="color: black;">{{i.name}}</a></h2></td>
            <td><h2>{{i.creation_date}}</h2></td>
        </tr>
        {% endfor %}
    </table>
        {% endif %}

        
            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
                
            <div style="height: 675px;"></div>
</body>
</html>

AWS_S3/buckets/templates/buckets/files.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>


    <style>
    
        body{
    
    background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
    }
    
        th, td {
      border-bottom: 1px solid rgb(173, 167, 206);
    }
    
    table{
    
        padding: 5px;
        font-family: serif;
    }
    input{
                margin: 3px;
             border: 1px solid red; 
                padding: 7px; 
                margin-top: 40px;
                margin-left: 40px;
            }
    .text{
                border-radius:10px 10px;
                padding: 10px;
                transition:1s;
            }
            .button{
                color:white;
                padding:10px;
                text-align:center;
                cursor:pointer;
                background-color: rgb(66, 19, 119);
                transition: 1s;
                border-radius:10px 10px;
            }
            .button:hover{
                transform:translate(0,-3px);
                background:black;
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
            }
    
    </style>


</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <div style="width: 30%;float:left">
<div>
    <input type="submit" class="button" value="List Files" name="lf">
    <button class="button" style=" margin-left:40px;"><a href="upld.html" style="color: white; "> Upload</a></button>
</div>
        <input type="text" placeholder="Enter File name" name="fname" class="text">
<div>
    <input type="submit" class="button" value="Create File" name="crf">
    <input type="submit" class="button" value="Delete File" name="df"> 
</div>

<div>
    <input type="submit" class="button" value="Create Folder" name="crfo">
    <input type="submit" class="button" value="Delete Folder" name="dfo">
</div>
    </div>
<div style="width: 70%; float:right">
    </form>
    {% if lfs %}
    <table>
        <tr>
            <th><h1>File Name</h1></th>

        </tr>
        {% for i in lfs %}
        <tr>
            <td><h2>{{i}}</h2></td>
        </tr>
        {% endfor %}
    </table>
        {% endif %}
    </div>

    <br><br>    
            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
        <div style="height:435px ;"></div>        
        
</body>
</html>

AWS_S3/buckets/templates/buckets/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

<style>
        *{
            box-sizing:border-box
            
        }
        div{
            width:100px ;
            display:flex;
            justify-content:space-evenly;
            align-items:center;
          
        }
        body{
            background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
        }
        input{
            margin: 3px;
         border: 1px solid red; 
            padding: 7px; 
        }
        .text{
            border-radius:10px 10px;
            padding: 10px;
            transition:1s;
        }
        .text:hover{
            box-shadow: inset 0 12px 16px 0 rgba(0,0,0,0.10),0 17px 50px 0 rgba(0,0,0,0.19);
        } 
        .button{
            color:white;
            padding:10px;
            text-align:center;
            cursor:pointer;
            background-color: rgb(66, 19, 119);
            transition: 1s;
            border-radius:10px 10px;
        }
        .button:hover{
            transform:translate(0,-3px);
            background:black;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
        h1{
            border-radius:10px 10px;
    
            transition:1s; 
        }
</style>

</head>
<body>
    <form method="POST">
        {% csrf_token %}
 <center style="margin-top: 10%;">
    <div>
        <input type="text" placeholder="Enter Access Key Id" name="aid" class="text">
        <input type="text" placeholder="Enter Seceret Access Key" name="sak" class="text"><br>
        </div><br><br>
        <div>
            <input type="submit" class="button" value="verify" name="log" style="margin-right: 150px;">
    
        {% if s %}
        <button class="button"><a style="color:white" href="{% url 'buckets:login' %}"> Login </a></button>
        {% endif %}
    </div>
   
   
   
    </form>
 
 </center>

    
        <marquee behavior="alternate" direction="">
            <h1>
                {% if messages %}
                {% for n in messages %}
                <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                {% endfor %}
                {% endif %}
            </h1>
        </marquee>
        <div style="height:500px ;">
        </div>

            


</body>
</html>

AWS_S3/buckets/templates/buckets/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
<style>
            body{

                background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
}

ul {
  list-style-type: none;
  width: 100%;
  margin-top: 40px;
  padding: 0;
  overflow: hidden;
  display:flex;
            justify-content:space-evenly;
}

li {
  float: left;
  
}
.button{
            color:white;
            padding:10px;
            text-align:center;
            cursor:pointer;
            background-color: rgb(66, 19, 119);
            transition: 1s;
            border-radius:10px 10px;
}
button{
            color:white;
            padding:10px;
            text-align:center;
            cursor:pointer;
            background-color: rgb(66, 19, 119);
            transition: 1s;
            border-radius:10px 10px;
}
.button:hover{
            transform:translate(0,-3px);
            background:black;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
button:hover{
            transform:translate(0,-3px);
            background:black;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
a{
    color: white;
}
th, td {
      border-bottom: 1px solid rgb(173, 167, 206);
    }
    
    table{
    
        padding: 5px;
        font-family: serif;
    }


</style>

</head>
<body>
    <form method="POST">
        {% csrf_token %}
        <ul>
            <li><input type="submit" class="button" value="List Bucket" name="lb"></li>
            <button><a href="{% url 'buckets:create' %}"> Create </a></button>
            <button><a href="{% url 'buckets:delete' %}"> Delete </a></button>
            <button><a href="{% url 'buckets:copy' %}"> Copy </a></button>
            <button><a href="{% url 'buckets:move' %}"> Move</a></button>
        </ul>
        
        
        
        
        

    </form>
    {% if lbs %}
    <table>
        <tr>
            <th><h1>Bucket Name</h1></th>
            <th><h1>Creation Date</h1></th>
        </tr>
        {% for i in lbs %}
        <tr>
            <td><h2><a href="{{i.name}}" style="color: black;"">{{i.name}}</a></h2></td>
            <td><h2>{{i.creation_date}}</h2></td>
        </tr>
        {% endfor %}
    </table>
        {% endif %}

        
            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
                
        
        <div style="height:670px ;"></div>
</body>
</html>

AWS_S3/buckets/templates/buckets/move.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
        *{
            box-sizing:border-box
            
        }
        
        
        body{
            background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
        }
        input{
            margin: 3px;
         border: 1px solid red; 
            padding: 7px; 
            margin: 10px;
        }
        .text{
            border-radius:10px 10px;
            padding: 10px;
            transition:1s;
        }
        .text:hover{
            box-shadow: inset 0 12px 16px 0 rgba(0,0,0,0.10),0 17px 50px 0 rgba(0,0,0,0.19);
        } 
        .button{
            color:white;
            padding:10px;
            text-align:center;
            cursor:pointer;
            background-color: rgb(66, 19, 119);
            transition: 1s;
            border-radius:10px 10px;
        }
        .button:hover{
            transform:translate(0,-3px);
            background:black;
            box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
        }
        h1{
            border-radius:10px 10px;
    
            transition:1s; 
        }
</style>




</head>
<body>
    <form method="POST">
        {% csrf_token %}

<center style="margin-top: 100px;">
    <div>
        <input type="text" placeholder="Source Bucket name (*)" name="sbname" class="text">
        <input type="text" placeholder="Source File name (*)" name="sfname" class="text">
       </div>
       <div> 
        <input type="text" placeholder="Destination Bucket name (*)" name="dbname" class="text" style="margin-right: 120px;">
        <input type="submit" class="button" value="Move File" name="mf"> 
    </div>

</center>
        
    </form>

            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
                
            <div style="height:550px ;"></div>

</body>
</html>

AWS_S3/buckets/templates/buckets/upld.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <style>
    
        body{
    
    background-image: linear-gradient(180deg, rgb(22, 23, 102), rgb(70, 196, 201));
    }
    
        th, td {
      border-bottom: 1px solid rgb(173, 167, 206);
    }
    
    table{
    
        padding: 5px;
        font-family: serif;
    }
    input{
                margin: 3px;
             border: 1px solid red; 
                padding: 7px; 
                margin-top: 40px;
                margin-left: 40px;
            }
    .text{
                border-radius:10px 10px;
                padding: 10px;
                transition:1s;
            }
            .button{
                color:white;
                padding:10px;
                text-align:center;
                cursor:pointer;
                background-color: rgb(66, 19, 119);
                transition: 1s;
                border-radius:10px 10px;
            }
            .button:hover{
                transform:translate(0,-3px);
                background:black;
                box-shadow: 0 12px 16px 0 rgba(0,0,0,0.24),0 17px 50px 0 rgba(0,0,0,0.19);
            }
         </style>    

</head>
<body>
    <form method="POST">
        {% csrf_token %}

        <input type="file" value="Enter File path" name="fp" class="text">
        <input type="submit" class="button" value="Upload File" name="uf"> 
    </form>
    {% if lfs %}
    <table>
        <tr>
            <th><h1>File Name</h1></th>
            <th><h1>Creation Date</h1></th>
        </tr>
        {% for i in lfs %}
        <tr>
            <td><h2>{{i}}</h2></td>
        </tr>
        {% endfor %}
    </table>
        {% endif %}

    
            <marquee behavior="alternate" direction="">
                <h1>
                    {% if messages %}
                    {% for n in messages %}
                    <h2 style="color: rgb(116, 28, 28);font-family: monospace; font-size: xx-large;">{{n}}</h2>
                    {% endfor %}
                    {% endif %}
                </h1>
            </marquee>
    
            <div style="height: 670px;"></div>
        
</body>
</html>